minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
blockExoticSubdeps: true
allowBuilds:
  core-js-pure: true
  esbuild: true
  sharp: true
  workerd: true
peerDependencyRules:
  allowedVersions:
    react: '19'
enableGlobalVirtualStore: true
